version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /var/log/nginx:/var/log/nginx
    networks:
      custom_net:
        ipv4_address: 172.20.8.2

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.8.0/24
